spring:
  application:
    name: gestaodetarefas
  datasource:
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.olabpyzssqdtepqkharl&password=romeusoaresdesouto
    username: postegres
    password: romeusoaresdesouto
  jpa:
    hibernate:
      ddl-auto: update
